//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCiclo3.MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumidores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consumidores()
        {
            this.Pagos = new HashSet<Pagos>();
        }
    
        public int idConsumidor { get; set; }
        public string nombresConsumidor { get; set; }
        public string apellidosConsumidor { get; set; }
        public string numeroDocumento { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public Nullable<int> idComunidad_FK { get; set; }
    
        public virtual Comunidades Comunidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }
    }
}
